data<-read.table("household_power_consumption.txt",sep=";",header=TRUE,stringsAsFactors=FALSE, dec=".")
power_consumption<-subset(data,data$Date %in% c("1/2/2007","2/2/2007"))
date_time <- strptime(paste(power_consumption$Date,power_consumption$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
png("plot2.png",width=480,height=480)
plot(date_time,as.numeric(power_consumption$Global_active_power),col="red",type="l" ,ylab="Global Active Power (kilowatts)")
dev.off()
