data<-read.table("household_power_consumption.txt",sep=";",header=TRUE,stringsAsFactors=FALSE, dec=".")
power_consumption<-subset(data,data$Date %in% c("1/2/2007","2/2/2007"))
date_time <- strptime(paste(power_consumption$Date,power_consumption$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
png("plot3.png", width=480, height=480)
plot(date_time, as.numeric(power_consumption$Sub_metering_1), type="l", ylab="Energy Submetering",xlab="")
lines(date_time, as.numeric(power_consumption$Sub_metering_2), type="l", col="red")
lines(date_time, as.numeric(power_consumption$Sub_metering_3), type="l", col="blue")
legend("topright", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))
dev.off()